### ISSUE TITLE
A question about the content

### ISSUE THREAD

**Issue by strawberry-choco** [luongvo209/Short-Gitlab-Tutorial#4]
> While there are not much options for creating a new project(repository) on Github, there are a bunch of options to choose from, notably:

Do you really mean Github or actually Gitlab?

**Comment by luong-komorebi** [comment]
Hi @chrunchyjesus, in this paragraph I am talking about Github. I am particularly mentioning this page. It is very simple and provide few options to choose from.    
![image](https://user-images.githubusercontent.com/15828926/41326419-1c5ba67c-6ee9-11e8-818a-567ce95c83c2.png)

Even the import page is simple, too : 
![image](https://user-images.githubusercontent.com/15828926/41326458-440c4780-6ee9-11e8-9957-273ca54787ff.png)  

There are a bunch of options if you look at Gitlab side :)

**Comment by strawberry-choco** [comment]
Thanks. :)

What about `Unlike the limited choice on Github, Gitlab has a bunch of options to choose from, notably:`.

**Comment by luong-komorebi** [comment]
@chrunchyjesus  Yeah that would sound good. In fact we don't need to change that much. I think what is missing in my sentence is a proper reference to Gitlab, which makes it confusing to understand 😄

**Comment by strawberry-choco** [comment]
Then `While there are not many options for creating new projects (=repositories) on Github, Gitlab has a bunch of options to choose from, notably:`.

**Comment by luong-komorebi** [comment]
YES this is it 🤣 Sorry I am busy at work can't make a commit right now

**Comment by strawberry-choco** [comment]
Don't worry, I did it for you. :) #7
